plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom' version '1.17.12'
}

group = project.maven_group
version = project.mod_version
base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://cursemaven.com" }
    maven { url = "https://libraries.minecraft.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"


    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // na razie możesz zostawić lub zakomentować:
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "com.terraformersmc:modmenu:20.0.0-beta.4"

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
