pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
    }
}

rootProject.name = "noflamesmoke"